[package]

name = "haproxy-consul-rs"
version = "0.0.1"
authors = ["YoungKing <yanckin@gmail.com>"]

[[bin]] 
name = "hasu"

[dependencies.consul]
git = "https://github.com/youngking/consul-rust"

[dependencies.rustache]
git = "https://github.com/rustache/rustache"
